receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 5s
    send_batch_size: 512

  memory_limiter:
    check_interval: 1s
    limit_mib: 256

  resource:
    attributes:
      - key: service.namespace
        value: signspeak
        action: insert

exporters:
  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 200

  # Uncomment to export to Google Cloud
  # googlecloud:
  #   project: signspeak-20dff
  #   log:
  #     default_log_name: signspeak-backend

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers:  [otlp]
      processors: [memory_limiter, batch]
      exporters:  [logging]
    metrics:
      receivers:  [otlp]
      processors: [memory_limiter, batch]
      exporters:  [logging]
    logs:
      receivers:  [otlp]
      processors: [memory_limiter, batch]
      exporters:  [logging]

  telemetry:
    logs:
      level: info
    metrics:
      level: detailed
      address: "0.0.0.0:8888"
